--Ximan Liu
--CSC 452
--prog4b

SET SERVEROUTPUT ON;
DECLARE
TYPE DEPTList IS VARRAY(5) OF NUMBER;
DEPTS DEPTList := DEPTList(0, 0, 0, 0, 0);
BEGIN
DEPTS(1) := 10;
DEPTS(2) := 20;
DEPTS(3) := 30;
DEPTS(4) := 40;
DEPTS(5) := 50;
FOR i IN DEPTS.FIRST..DEPTS.LAST LOOP
IF DEPTS(i) = 10 THEN
INSERT INTO DEPT VALUES (10, 'ACCOUNTING', 'NEW YORK');
END IF;
IF DEPTS(i) = 20 THEN
INSERT INTO DEPT VALUES (20, 'RESEARCH', 'DALLAS');
END IF;
IF DEPTS(i) = 30 THEN
INSERT INTO DEPT VALUES (30, 'SALES', 'CHICAGO');
END IF;
IF DEPTS(i) = 40 THEN
INSERT INTO DEPT VALUES (40, 'OPERATIONS', 'DALLAS');
END IF;
IF DEPTS(i) = 50 THEN
INSERT INTO DEPT VALUES (50, 'MARKETING', 'BOSTON');
END IF;
END LOOP;
END;
/

