--Ximan Liu
--CSC 452
--prog4a

DROP TABLE DEPT;
DROP TABLE DEPT_SHADOW;

CREATE TABLE DEPT(
DEPTNO NUMBER(3) PRIMARY KEY,
DNAME VARCHAR2(16),
LOC VARCHAR2(16));

CREATE TABLE DEPT_SHADOW(
DEPTNO NUMBER(3) PRIMARY KEY,
DNAME VARCHAR2(16),
LOC VARCHAR2(16),
USERNAME VARCHAR2(32),
MODTIME CHAR(17));

DROP TRIGGER insert_DEPT_SHADOW;

CREATE OR REPLACE TRIGGER insert_DEPT_SHADOW
AFTER INSERT ON DEPT
FOR EACH ROW
BEGIN
INSERT INTO DEPT_SHADOW VALUES(
:NEW.DEPTNO,
:NEW.DNAME,
:NEW.LOC,
USER,
TO_CHAR(SYSDATE, 'MM/DD/YY hh:mm:ss'));
END;
/

