--Ximan Liu
--CSC 452
--prog4c

SET SERVEROUTPUT ON;
DECLARE
type p_DEPT is table of VARCHAR2(40);
v_DEPTNO p_DEPT;
v_DNAME p_DEPT;
v_LOC p_DEPT;
BEGIN
SELECT DEPTNO, DNAME, LOC
BULK COLLECT INTO v_DEPTNO, v_DNAME, v_LOC
FROM DEPT;
FOR i IN 1..v_DEPTNO.COUNT LOOP
DBMS_OUTPUT.PUT_LINE('DEPTNO: '|| v_DEPTNO(i) ||'| DNAME: '||v_DNAME(i) ||'| LOC: '||v_LOC(i)); 
END LOOP;
END;
/

