--Ximan Liu
--CSC 452
--prog1c.sql
DESCRIBE STUDENT;
SELECT * FROM STUDENT;

DESCRIBE COURSE;
SELECT * FROM COURSE;

DESCRIBE ENROLLMENT;
SELECT * FROM ENROLLMENT;

DESCRIBE FACULTY;
SELECT * FROM FACULTY;