--Ximan Liu
--CSC 452
--prog1a.sql


DROP TABLE STUDENT;
DROP TABLE COURSE;
DROP TABLE ENROLLMENT;
DROP TABLE FACULTY;


CREATE TABLE STUDENT(
student_id VARCHAR2(25) NOT NULL,
std_name VARCHAR2(25) NOT NULL,
home_phone CHAR(12) NOT NULL,
total_credits NUMBER DEFAULT 0,
gpa NUMBER(9,2) DEFAULT 0,
advisor_id VARCHAR2(25) NOT NULL,
PRIMARY KEY(student_id)
);


CREATE TABLE COURSE(
course# CHAR(12) NOT NULL,
credit_hours NUMBER NOT NULL,
time NUMBER NOT NULL,
location VARCHAR2(25) NOT NULL,
faculty_id VARCHAR2(25) NOT NULL,
PRIMARY KEY(course#)
);


CREATE TABLE ENROLLMENT(
student_id VARCHAR2(25) NOT NULL,
course# CHAR(12) NOT NULL,
grade NUMBER(9,2) DEFAULT 0,
PRIMARY KEY(student_id, course#)
);


CREATE TABLE FACULTY(
faculty_id VARCHAR2(25) NOT NULL,
fac_name VARCHAR2(25) NOT NULL,
office VARCHAR2(25) NOT NULL,
salary NUMBER(9,2) DEFAULT 0,
PRIMARY KEY(faculty_id));


