--Ximan Liu
--CSC 452
--prog3d


DROP TABLE emp;
DROP TABLE dept;


SET SERVEROUTPUT ON;
DECLARE
table1 VARCHAR2(1000);
table2 VARCHAR2(1000);
insert1 VARCHAR2(1000);
insert2 VARCHAR2(1000);

DEPTNO NUMBER(3);
DNAME VARCHAR2(16);
LOC VARCHAR2(16);

EMPNO NUMBER(4);
ENAME VARCHAR2(16);
JOB VARCHAR2(16);
MGR NUMBER(4);
HIREDATE DATE;
SAL NUMBER(7,2);
COMM NUMBER(7,2);
EDEPTNO NUMBER(3);

BEGIN
table1 := 'CREATE TABLE dept'||'('|| 'DEPTNO NUMBER(3) PRIMARY KEY,'||'DNAME VARCHAR2(16),'||'LOC VARCHAR2(16)'||')';
EXECUTE IMMEDIATE (table1);
insert1 := 'INSERT INTO dept VALUES(:DEPTNO, :DNAME, :LOC)';
table2 := 'CREATE TABLE emp'||'('|| 'EMPNO NUMBER(4),'||'ENAME VARCHAR2(16),'||'JOB VARCHAR2(16),' || 'MGR NUMBER(4),'||'HIREDATE DATE,'||'SAL NUMBER(7,2),' ||'COMM NUMBER(7,2),'||'DEPTNO NUMBER(3) NOT NULL REFERENCES DEPT(DEPTNO)'||')';
EXECUTE IMMEDIATE (table2);
insert2 := 'INSERT INTO emp VALUES(:EMPNO, :ENAME, :JOB, :MGR, :HIREDATE, :SAL, :COMM, :DEPTNO)';

DEPTNO := 10;
DNAME := 'ACCOUNTING';
LOC := 'NEW YORK';
EXECUTE IMMEDIATE(insert1) USING DEPTNO, DNAME, LOC;
COMMIT;

DEPTNO := 20;
DNAME := 'RESEARCH';
LOC := 'DALLAS';
EXECUTE IMMEDIATE(insert1) USING DEPTNO, DNAME, LOC;
COMMIT;

DEPTNO := 30;
DNAME := 'SALES';
LOC := 'CHICAGO';
EXECUTE IMMEDIATE(insert1) USING DEPTNO, DNAME, LOC;
COMMIT;

DEPTNO := 40;
DNAME := 'OPERATIONS';
LOC := 'WASHINGTON (D.C.)';
EXECUTE IMMEDIATE(insert1) USING DEPTNO, DNAME, LOC;
COMMIT;

DEPTNO := 50;
DNAME := 'MARKETING';
LOC := 'BOSTON';
EXECUTE IMMEDIATE(insert1) USING DEPTNO, DNAME, LOC;
COMMIT;

EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Error!');
       
EMPNO := 7839;
ENAME := 'KING';
JOB := 'PRESIDENT';
MGR := NULL;
HIREDATE := '17-NOV-81';
SAL := 5000;
COMM := NULL;
EDEPTNO := 10;
EXECUTE IMMEDIATE insert2 USING EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, EDEPTNO;
COMMIT;

EMPNO := 7698;
ENAME := 'BLAKE';
JOB := 'MANAGER';
MGR := 7839;
HIREDATE := '17-NOV-81';
SAL := 5000;
COMM := NULL;
EDEPTNO := 10;
EXECUTE IMMEDIATE insert2 USING EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, EDEPTNO;
COMMIT;

EMPNO := 7782;
ENAME :=  'CLARK';
JOB :=  'MANAGER';
MGR := 7839;
HIREDATE :=  '09-JUN-81';
SAL := 2450;
COMM :=  NULL;
EDEPTNO := 10;
EXECUTE IMMEDIATE insert2 USING EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, EDEPTNO;
COMMIT;

EMPNO := 7566;
ENAME :=  'JONES';
JOB :=  'MANAGER';
MGR := 7839;
HIREDATE :=  '02-APR-81';
SAL := 2975;
COMM :=  NULL;
EDEPTNO := 20;
EXECUTE IMMEDIATE insert2 USING EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, EDEPTNO;
COMMIT;

EMPNO := 7654;
ENAME :=  'MARTIN';
JOB :=  'SALESMAN';
MGR := 7698;
HIREDATE :=  '28-SEP-81';
SAL := 1250;
COMM := 1400;
EDEPTNO := 30;
EXECUTE IMMEDIATE insert2 USING EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, EDEPTNO;
COMMIT;

EMPNO := 7499;
ENAME :=  'ALLEN';
JOB :=  'SALESMAN';
MGR := 7698;
HIREDATE :=  '20-FEB-81';
SAL := 1600;
COMM := 300;
EDEPTNO := 30;
EXECUTE IMMEDIATE insert2 USING EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, EDEPTNO;
COMMIT;

EMPNO := 7844;
ENAME :=  'TURNER';
JOB :=  'SALESMAN';
MGR := 7698;
HIREDATE :=  '08-SEP-81';
SAL := 1500;
COMM :=  NULL;
EDEPTNO := 30;
EXECUTE IMMEDIATE insert2 USING EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, EDEPTNO;
COMMIT;

EMPNO := 7900;
ENAME :=  'JAMES';
JOB :=  'CLERK';
MGR := 7698;
HIREDATE :=  '03-DEC-81';
SAL := 950;
COMM :=  NULL;
EDEPTNO := 30;
EXECUTE IMMEDIATE insert2 USING EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, EDEPTNO;
COMMIT;

EMPNO := 7521;
ENAME :=  'WARD';
JOB :=  'SALESMAN';
MGR := 7698;
HIREDATE :=  '22-FEB-81';
SAL := 1250;
COMM := 500;
EDEPTNO := 30;
EXECUTE IMMEDIATE insert2 USING EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, EDEPTNO;
COMMIT;

EMPNO := 7902;
ENAME :=  'FORD';
JOB :=  'ANALYST';
MGR := 7566;
HIREDATE :=  '03-DEC-81';
SAL := 3000;
COMM :=  NULL;
EDEPTNO := 20;
EXECUTE IMMEDIATE insert2 USING EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, EDEPTNO;
COMMIT;

EMPNO := 7369;
ENAME :=  'SMITH';
JOB :=  'CLERK';
MGR := 7902;
HIREDATE :=  '17-DEC-81';
SAL := 800;
COMM :=  NULL;
EDEPTNO := 20;
EXECUTE IMMEDIATE insert2 USING EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, EDEPTNO;
COMMIT;

EMPNO := 7788;
ENAME :=  'SCOTT';
JOB :=  'ANALYST';
MGR := 7566;
HIREDATE :=  '09-DEC-82';
SAL := 4000;
COMM :=  NULL;
EDEPTNO := 20;
EXECUTE IMMEDIATE insert2 USING EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, EDEPTNO;
COMMIT;   

EMPNO := 7876;
ENAME :=  'ADAMS';
JOB :=  'CLERK';
MGR := 7788;
HIREDATE :=  '12-JAN-83';
SAL := 1100;
COMM :=  NULL;
EDEPTNO := 20;
EXECUTE IMMEDIATE insert2 USING EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, EDEPTNO;
COMMIT;   

EMPNO := 7934;
ENAME :=  'MILLER';
JOB :=  'CLERK';
MGR := 7782;
HIREDATE :=  '22-JAN-82';
SAL := 1300;
COMM :=  NULL;
EDEPTNO := 10;
EXECUTE IMMEDIATE insert2 USING EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, EDEPTNO;
COMMIT;    

EMPNO := 7698;
ENAME :=  'BLAKE';
JOB :=  'MANAGER';
MGR := 7839;
HIREDATE :=  '01-MAY-81';
SAL := 2850;
COMM :=  NULL;
EDEPTNO := 30;
EXECUTE IMMEDIATE insert2 USING EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, EDEPTNO;
COMMIT;

EMPNO := 7698;
ENAME :=  'BLAKE';
JOB :=  'MANAGER';
MGR := 7839;
HIREDATE :=  '01-MAY-81';
SAL := 2850;
COMM :=  NULL;
EDEPTNO := 30;
EXECUTE IMMEDIATE insert2 USING EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, EDEPTNO;
COMMIT;

END;
/

