--Ximan Liu
--CSC452
--Final Project
--Q1.sql

DROP TABLE CUSTOMER;
DROP TABLE CUSTOMER_SHADOW;

CREATE TABLE CUSTOMER(
CID NUMBER(3) NOT NULL PRIMARY KEY,
CName VARCHAR2(20) NOT NULL,
CLocation VARCHAR2(20) NOT NULL,
CState VARCHAR2(2) NOT NULL);

CREATE TABLE CUSTOMER_SHADOW(
CID NUMBER(3) NOT NULL PRIMARY KEY,
CName VARCHAR2(20) NOT NULL,
CLocation VARCHAR2(20) NOT NULL,
CState VARCHAR2(2) NOT NULL,
USERNAME VARCHAR2(32) NOT NULL,
MODTIME VARCHAR2(20) NOT NULL);

