--Ximan Liu
--CSC452
--Final Project
--Q3.sql

SET SERVEROUTPUT ON;
DECLARE
TYPE CUSTOMERList IS VARRAY(6) OF NUMBER;
CUSTOMERS CUSTOMERList := CUSTOMERList(0, 0, 0, 0, 0, 0);
BEGIN
CUSTOMERS(1) := 001;
CUSTOMERS(2) := 002;
CUSTOMERS(3) := 003;
CUSTOMERS(4) := 004;
CUSTOMERS(5) := 005;
CUSTOMERS(6) := 006;
FOR i IN CUSTOMERS.FIRST..CUSTOMERS.LAST LOOP
IF CUSTOMERS(i) = 001 THEN
INSERT INTO CUSTOMER VALUES (001, 'FURNITURE', 'PLANO', 'TX');
END IF;
IF CUSTOMERS(i) = 002 THEN
INSERT INTO CUSTOMER VALUES (002, 'MOUNTAIN', 'BOULDER', 'CO');
END IF;
IF CUSTOMERS(i) = 003 THEN
INSERT INTO CUSTOMER VALUES (003, 'GALLERY', 'SAINT ANTONIO', 'TX');
END IF;
IF CUSTOMERS(i) = 004 THEN
INSERT INTO CUSTOMER VALUES (004, 'STATE', 'DALLAS', 'TX');
END IF;
IF CUSTOMERS(i) = 005 THEN
INSERT INTO CUSTOMER VALUES (005, 'EVAN', 'CHICAGO', 'IL');
END IF;
IF CUSTOMERS(i) = 006 THEN
INSERT INTO CUSTOMER VALUES (006, 'BURG', 'NASHVILLE', 'CO');
END IF;
END LOOP;
END;
/

