--Ximan Liu
--CSC452
--Final Project
--zipcode.sql

DROP TABLE ZIPCODE;

CREATE TABLE ZIPCODE(
ZIP NUMBER(5) NOT NULL PRIMARY KEY,
CITY VARCHAR2(20) NOT NULL,
STATE VARCHAR2(2) NOT NULL,
LATITUDE NUMBER(2) NOT NULL,
DST NUMBER(1) NOT NULL);

